all:
  vars:
    ansible_ssh_private_key_file: sshkeys/sshkey
    ansible_user: root

# HAProxy
proxies:
  vars:
    haproxy_width_stats: true
    haproxy_with_auth: true
    haproxy_user: admin
    haproxy_password: 12345

  hosts:
    proxy01:
      ansible_host: 68.183.127.197

# Nginx Servers
webservers:
  hosts:
    webserver-01:
      ansible_host: 68.183.120.243
    webserver-02:
       ansible_host: 68.183.120.93
    webserver-03:
      ansible_host: 68.183.120.229
